version: '3.6'

volumes:
  www:

services:

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./nginx
    ports:
      - ${WORDPRESS_PORT}:80
    volumes:
      - "www:/var/www/html"

  wordpress:
    depends_on:
      - mysql
    build:
      context: ./wordpress
    environment:
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - "www:/var/www/html"

  mysql:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_HOST: "mysql"
        PMA_USER: "root"
        PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ports:
        - ${PHPMYADMIN_PORT}:80

  wp-cli:
    depends_on:
      - wordpress
    build:
      context: ./wp-cli
    environment:
      WORDPRESS_TITLE:
      WORDPRESS_LOGIN:
      WORDPRESS_PASSWORD:
      WORDPRESS_PORT:
      WORDPRESS_EMAIL:
    volumes:
      - "www:/var/www/html"
