version: '3.6'

volumes:
  certs:
  vhost:
  html:

# Images below are forks of:
#   https://github.com/jwilder/nginx-proxy
#   https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion


services:

  nginx-proxy:
    restart: always
    image: quay.io/bukow/nginx-proxy
#    labels:
#      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=
    ports:
      - 80:80
#      - 443:443
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
#
#  nginx-proxy-letsencrypt:
#
#    image: quay.io/bukow/nginx-proxy-letsencrypt
#    restart: always
#    depends_on:
#      - nginx-proxy
#    volumes:
#      - certs:/etc/nginx/certs
#      - vhost:/etc/nginx/vhost.d
#      - html:/usr/share/nginx/html
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#    environment:
#      DEFAULT_EMAIL:
#
