name: Bench

on: [push, pull_request]

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: docker-compose up
      run: docker-compose up -d --build --scale wrk=0 --scale wp-cli=0

    - name: install wordpress
      run: docker-compose up wp-cli

    - name: benchmark
      run: make bench

    - name: stats
      run: docker stats --no-stream
