name: Dev

on: [push, pull_request]

jobs:

  develop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: add $DOMAIN_NAME to hosts
      run: |
        source .env
        echo "127.0.0.1 ${DOMAIN_NAME}" | sudo tee -a /etc/hosts
      working-directory: ./services

    - name: permissions
      run: |
        chmod +x ./test.sh
        chmod +x ./test_http.sh
      working-directory: ./services

    - name: test
      run: ./test.sh
      working-directory: ./services

    - name: show logs
      if: failure()
      run: |
        cat /etc/hosts
        make log-dev
        make log-deploy
        make proxy-config
        docker ps
        docker stats --no-stream
        docker network ls
        make nginx-perms
        make wordpress-perms

      working-directory: ./services

    - name: docker ps
      run: docker ps

    - name: docker stats
      run: docker stats --no-stream

    - name: show logs
      run: |
        make log-deploy
        make proxy-config
        docker network ls
        make nginx-perms
        make wordpress-perms
      working-directory: ./services
