name: Dev

on: [push, pull_request]

jobs:

  develop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: permissions
      run: |
        chmod +x ./test.sh
        chmod +x ./test_http.sh
      working-directory: ./services

    - name: test
      run: ./test.sh
      working-directory: ./services

    - name: show logs
      if: failure()
      run: make log-dev && make log-deploy && make log-proxy

    - name: docker ps
      run: docker ps

    - name: docker stats
      run: docker stats --no-stream
