name: Dev

on: [push, pull_request]

jobs:

  develop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: test
      run: ./test.sh
      working-directory: ./services

    - name: docker ps
      run: docker ps

    - name: docker stats
      run: docker stats --no-stream
